title: shared-project
description: shared-project
theme: just-the-docs
color_scheme: dark

search_enabled: false

callouts:
  note:
    title: note
    color: blue
  warn:
    title: warning
    color: yellow
  danger:
    title: danger
    color: red
